name: Get data

on:
  schedule:
  - cron:  '*/15 * * * *'
  # Also allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # cf. https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    # cf. https://github.com/peter-murray/reset-workspace-ownership-action
    - name: Get Actions user id
      id: get_uid
      run: |
        actions_user_id=`id -u $USER`
        echo $actions_user_id
        echo ::set-output name=uid::$actions_user_id

    - name: Correct Ownership in GITHUB_WORKSPACE directory
      uses: peter-murray/reset-workspace-ownership-action@v1
      with:
        user_id: ${{ steps.get_uid.outputs.uid }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Run Python script
      run: |
        python bsm.py
   
    - name: Push data to repo
      uses: github-actions-x/commit@v2.7
      with:
        push-branch: 'main'
        commit-message: 'Add current data'
        force-add: 'true'
        files: 20*.zip
        name: autoupdate
